language: haskell

ghc:
  - 7.8
  
global:
  - SKIP_HADDOCK=1


script:
  - cabal install --only-dependencies && cabal configure && cabal build

before_install:
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update
  - cabal update
  - cabal sandbox init
  - cabal sandbox add-source FontyFruity

install:
  - cabal install --force-reinstalls

notifications:
  email:
      - twinside@gmail.com

